## -*- coding: utf-8 -*-

import sys

with open(sys.argv[1],"r") as file:
	output = open(sys.argv[1]+"-ASCII","w")
	data = file.read()
	
	for sym in data:
		if sym == " ": output.write("0")
		elif sym == "!": output.write("1")
		elif sym == "\"": output.write("2")
		elif sym == "#": output.write("3")
		elif sym == "$": output.write("4")
		elif sym == "%": output.write("5")
		elif sym == "&": output.write("6")
		elif sym == "\'": output.write("7")
		elif sym == "(": output.write("8")
		elif sym == ")": output.write("9")
		elif sym == "@": output.write("A")
		elif sym == "A": output.write("B")
		elif sym == "B": output.write("C")
		elif sym == "C": output.write("D")
		elif sym == "D": output.write("E")
		elif sym == "F": output.write("F")
		elif sym == "G": output.write("G")
		elif sym == "I": output.write("H")
		elif sym == "J": output.write("I")
		elif sym == "K": output.write("J")
		elif sym == "L": output.write("K")
		elif sym == "M": output.write("L")
		elif sym == "N": output.write("M")
		elif sym == "O": output.write("N")
		elif sym == "P": output.write("O")
		elif sym == "Q": output.write("P")
		elif sym == "S": output.write("Q")
		elif sym == "T": output.write("R")
		elif sym == "U": output.write("S")
		elif sym == "V": output.write("T")
		elif sym == "W": output.write("U")
		elif sym == "X": output.write("V")
		elif sym == "Y": output.write("W")
		elif sym == "Z": output.write("X")
		elif sym == "[": output.write("Y")
		elif sym == "\\": output.write("Z")
		elif sym == "`": output.write("a")
		elif sym == "a": output.write("b")
		elif sym == "b": output.write("c")
		elif sym == "c": output.write("d")
		elif sym == "d": output.write("e")
		elif sym == "f": output.write("f")
		elif sym == "g": output.write("g")
		elif sym == "i": output.write("h")
		elif sym == "j": output.write("i")
		elif sym == "k": output.write("j")
		elif sym == "l": output.write("k")
		elif sym == "m": output.write("l")
		elif sym == "n": output.write("m")
		elif sym == "o": output.write("n")
		elif sym == "p": output.write("o")
		elif sym == "q": output.write("p")
		elif sym == "s": output.write("q")
		elif sym == "t": output.write("r")
		elif sym == "u": output.write("s")
		elif sym == "v": output.write("t")
		elif sym == "w": output.write("u")
		elif sym == "x": output.write("v")
		elif sym == "y": output.write("w")
		elif sym == "z": output.write("x")
		elif sym == "{": output.write("y")
		elif sym == "|": output.write("z")
		elif sym == "1": output.write("+")
		elif sym == "3": output.write("/")
		elif sym == "8": output.write("=")
		elif sym == "\n": output.write("\n")
		
	output.close()
