## -*- coding: utf-8 -*-

import sys

with open(sys.argv[1],"r") as file:
	output = open(sys.argv[1]+"-DKOTI","w")
	data = file.read()
	
	for sym in data:
		if sym == "0": output.write(" ")
		elif sym == "1": output.write("!")
		elif sym == "2": output.write("\\\"")
		elif sym == "3": output.write("#")
		elif sym == "4": output.write("$")
		elif sym == "5": output.write("%")
		elif sym == "6": output.write("&")
		elif sym == "7": output.write("\\\'")
		elif sym == "8": output.write("(")
		elif sym == "9": output.write(")")
		elif sym == "A": output.write("@")
		elif sym == "B": output.write("A")
		elif sym == "C": output.write("B")
		elif sym == "D": output.write("C")
		elif sym == "E": output.write("D")
		elif sym == "F": output.write("F")
		elif sym == "G": output.write("G")
		elif sym == "H": output.write("I")
		elif sym == "I": output.write("J")
		elif sym == "J": output.write("K")
		elif sym == "K": output.write("L")
		elif sym == "L": output.write("M")
		elif sym == "M": output.write("N")
		elif sym == "N": output.write("O")
		elif sym == "O": output.write("P")
		elif sym == "P": output.write("Q")
		elif sym == "Q": output.write("S")
		elif sym == "R": output.write("T")
		elif sym == "S": output.write("U")
		elif sym == "T": output.write("V")
		elif sym == "U": output.write("W")
		elif sym == "V": output.write("X")
		elif sym == "W": output.write("Y")
		elif sym == "X": output.write("Z")
		elif sym == "Y": output.write("[")
		elif sym == "Z": output.write("\\\\")
		elif sym == "a": output.write("`")
		elif sym == "b": output.write("a")
		elif sym == "c": output.write("b")
		elif sym == "d": output.write("c")
		elif sym == "e": output.write("d")
		elif sym == "f": output.write("f")
		elif sym == "g": output.write("g")
		elif sym == "h": output.write("i")
		elif sym == "i": output.write("j")
		elif sym == "j": output.write("k")
		elif sym == "k": output.write("l")
		elif sym == "l": output.write("m")
		elif sym == "m": output.write("n")
		elif sym == "n": output.write("o")
		elif sym == "o": output.write("p")
		elif sym == "p": output.write("q")
		elif sym == "q": output.write("s")
		elif sym == "r": output.write("t")
		elif sym == "s": output.write("u")
		elif sym == "t": output.write("v")
		elif sym == "u": output.write("w")
		elif sym == "v": output.write("x")
		elif sym == "w": output.write("y")
		elif sym == "x": output.write("z")
		elif sym == "y": output.write("{")
		elif sym == "z": output.write("|")
		elif sym == "+": output.write("1")
		elif sym == "/": output.write("3")
		elif sym == "=": output.write("8")
		elif sym == "\n": output.write("\n")
		
	output.close()
